# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HanoiCli < Formula
  desc "Interactive rebalance advisor for Kubernetes"
  homepage "https://github.com/k-krew/hanoi-cli"
  version "1.0.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/k-krew/hanoi-cli/releases/download/v1.0.0/hanoi-cli_1.0.0_darwin_amd64.tar.gz"
      sha256 "31a8429c29964307982ee54fa38c35b5d190fb597e66240854e101c2efd6495e"

      define_method(:install) do
        bin.install "hanoi-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/k-krew/hanoi-cli/releases/download/v1.0.0/hanoi-cli_1.0.0_darwin_arm64.tar.gz"
      sha256 "8b73700bf3f3cc99690d1943a713fe8ae29a3fe940a36794d73674f34759a879"

      define_method(:install) do
        bin.install "hanoi-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/k-krew/hanoi-cli/releases/download/v1.0.0/hanoi-cli_1.0.0_linux_amd64.tar.gz"
      sha256 "852f5cb5f3ebd90edfc7b3160c27bf15ede98662c8e25fa0745ce556b43b917f"
      define_method(:install) do
        bin.install "hanoi-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/k-krew/hanoi-cli/releases/download/v1.0.0/hanoi-cli_1.0.0_linux_arm64.tar.gz"
      sha256 "473d04a6549daa3b9261f99d5625f4c38538a2891b66234cdff7429931e482b2"
      define_method(:install) do
        bin.install "hanoi-cli"
      end
    end
  end

  test do
    system "#{bin}/hanoi-cli", "--help"
  end
end
