# This file was generated by GoReleaser. DO NOT EDIT.
cask "argazer" do
  version "1.1.5"

  on_macos do
    on_intel do
      sha256 "7eb6c51ef421330f8e76d508091a982a1f8b26682351757d76904cfa06da7ace"
      url "https://github.com/k-krew/argazer/releases/download/v#{version}/argazer_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "fce1a073cefb05e0fc2f79b3c68d04a3ba477ffb5326ef1e69cd0b60117d6705"
      url "https://github.com/k-krew/argazer/releases/download/v#{version}/argazer_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f824f8946cec9b5d11a08f7f38c42e403baaaecd4bdcc47032d4220608df8cba"
      url "https://github.com/k-krew/argazer/releases/download/v#{version}/argazer_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8986619a48e278a1e88256ed2e54be5d3dbc0384a544109bb81ad1c30d301e71"
      url "https://github.com/k-krew/argazer/releases/download/v#{version}/argazer_#{version}_linux_arm64.tar.gz"
    end
  end

  name "argazer"
  desc "Monitor ArgoCD applications for Helm chart updates"
  homepage "https://github.com/kreicer/argazer"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "argazer"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/argazer"]
    end
  end

  # No zap stanza required

end
