# This file was generated by GoReleaser. DO NOT EDIT.
cask "argazer" do
  version "2.0.0"

  on_macos do
    on_arm do
      sha256 "8c021a7ab94a5ba4d0b81fff18cb08e0e04f416b8928806049be619c214a8624"
      url "https://github.com/k-krew/argazer/releases/download/v#{version}/argazer_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "70692539ae60250c44d6a67444441c3f8fec0f2908dfee63e000d2266ccce057"
      url "https://github.com/k-krew/argazer/releases/download/v#{version}/argazer_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ad8c67ea4e80c0d054deddd3341b13dc94e6800b9fbaa1423b55d37a07bc70b0"
      url "https://github.com/k-krew/argazer/releases/download/v#{version}/argazer_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f22b60e2be5cc61b6bfced2ffdac8baeb80f7b7a7343f5d6ef1a6285481ac719"
      url "https://github.com/k-krew/argazer/releases/download/v#{version}/argazer_#{version}_linux_amd64.tar.gz"
    end
  end

  name "argazer"
  desc "Monitor ArgoCD applications for Helm chart updates"
  homepage "https://github.com/kreicer/argazer"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "argazer"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/argazer"]
    end
  end

  # No zap stanza required
end
