# This file was generated by GoReleaser. DO NOT EDIT.
cask "columbo" do
  version "1.0.1"

  on_macos do
    on_intel do
      sha256 "57b9afea6dff8695b0ce61598305e44202e3c00776f8352946afd2fb1ced8cf6"
      url "https://github.com/k-krew/columbo/releases/download/v#{version}/columbo_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ddd0ad9593371efd2f22ca234e0e7298d5d6eedd36f67bf1f2e2ba1147957c21"
      url "https://github.com/k-krew/columbo/releases/download/v#{version}/columbo_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0f3b1609c07eca0ca0c31b4ab8743d170f022beeb4f0cf5f3227209f9ce0ddfb"
      url "https://github.com/k-krew/columbo/releases/download/v#{version}/columbo_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "802b40287e6078f0e1e2badcffc08c955e594f30355cf651c8985984d6dfc92e"
      url "https://github.com/k-krew/columbo/releases/download/v#{version}/columbo_#{version}_linux_arm64.tar.gz"
    end
  end

  name "columbo"
  desc "Identify suspicious Kubernetes pods using a score"
  homepage "https://github.com/k-krew/columbo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "columbo"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/columbo"]
    end
  end

  # No zap stanza required

end
