# This file was generated by GoReleaser. DO NOT EDIT.
cask "columbo" do
  version "1.1.1"

  on_macos do
    on_intel do
      sha256 "920a7851d84c2cbe6ce56b89d9a3846d8892f511ea95af20815846c9da53efc8"
      url "https://github.com/k-krew/columbo/releases/download/v#{version}/columbo_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "04060c10ab9bb98172d8aff7ef6dfda864df8a7716cf3a35297754a405effa34"
      url "https://github.com/k-krew/columbo/releases/download/v#{version}/columbo_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8f67c10ba8474dd49b79b85d0820b39a8a9cce7bfcaec4ca3555648cf9c8a173"
      url "https://github.com/k-krew/columbo/releases/download/v#{version}/columbo_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0e2c9b2dff0c5473d1bd81ed01f9dbe6a201ee6964e47cec50a39c3d23cb315e"
      url "https://github.com/k-krew/columbo/releases/download/v#{version}/columbo_#{version}_linux_arm64.tar.gz"
    end
  end

  name "columbo"
  desc "Identify suspicious Kubernetes pods using a score"
  homepage "https://github.com/k-krew/columbo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "columbo"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/columbo"]
    end
  end

  # No zap stanza required

end
