# This file was generated by GoReleaser. DO NOT EDIT.
cask "columbo" do
  name "columbo"
  desc "Identify suspicious Kubernetes pods using a score"
  homepage "https://github.com/k-krew/columbo"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "columbo"

  on_macos do
    on_intel do
      url "https://github.com/k-krew/columbo/releases/download/v#{version}/columbo_#{version}_darwin_amd64.tar.gz"
      sha256 "139ecc2cb838646c074e8e60f1f68a72ef8107f46dfb5c384b671ea1b2b87f50"
    end
    on_arm do
      url "https://github.com/k-krew/columbo/releases/download/v#{version}/columbo_#{version}_darwin_arm64.tar.gz"
      sha256 "8479a7d969566d83cec7fab842e4e29bc564bf76620ab13126694ee1a3740ef9"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/k-krew/columbo/releases/download/v#{version}/columbo_#{version}_linux_amd64.tar.gz"
      sha256 "c9049a2da5d8720b56005002619dc6ad38b3e8988819b0051d63dec7cdcf0360"
    end
    on_arm do
      url "https://github.com/k-krew/columbo/releases/download/v#{version}/columbo_#{version}_linux_arm64.tar.gz"
      sha256 "d38289417d394facf620699b62363bf01bde00d21715097634e4a4a73e9ea6bf"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/columbo"]
    end
  end

  # No zap stanza required
end
