# This file was generated by GoReleaser. DO NOT EDIT.
cask "hanoi-cli" do
  version "1.0.2"

  on_macos do
    on_intel do
      sha256 "f20b5c17b1b04e6cc3e5b3234083d632af01a2b4a92fbd521e6e247bf5e57977"
      url "https://github.com/k-krew/hanoi-cli/releases/download/v#{version}/hanoi-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e82527cfaf6e4bc642858c213fd311ac5ffc7cc6ced67dc71217bca9849445f7"
      url "https://github.com/k-krew/hanoi-cli/releases/download/v#{version}/hanoi-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2fbe69d10a1172a234cd113cf67d552867427ee2b405b77eee652ebefe60740d"
      url "https://github.com/k-krew/hanoi-cli/releases/download/v#{version}/hanoi-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3d042f4cc1bd2d58f374af67fab3af2971382837f5214a14d55e9ca215dacf37"
      url "https://github.com/k-krew/hanoi-cli/releases/download/v#{version}/hanoi-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "hanoi-cli"
  desc "Interactive rebalance advisor for Kubernetes"
  homepage "https://github.com/k-krew/hanoi-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hanoi-cli"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hanoi-cli"]
    end
  end

  # No zap stanza required

end
