# This file was generated by GoReleaser. DO NOT EDIT.
cask "hanoi-cli" do
  version "1.1.2"

  on_macos do
    on_intel do
      sha256 "a86cc8429ac831bf009e6d6e2905a19c28f52d7510cbb5ad931fa6c1a368dca7"
      url "https://github.com/k-krew/hanoi-cli/releases/download/v#{version}/hanoi-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "68618594e786f2769deac54486e1bfd92aba67aa36d80f9a2d9330ee5d01f901"
      url "https://github.com/k-krew/hanoi-cli/releases/download/v#{version}/hanoi-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c8857bf921802cf14b047e2095facb43c3d9f73d04f879ab2c4925a1c3dea8e6"
      url "https://github.com/k-krew/hanoi-cli/releases/download/v#{version}/hanoi-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e9d07e9e61293e68f4f76e10bde445d41f680762b03952a119e23dc391fffc78"
      url "https://github.com/k-krew/hanoi-cli/releases/download/v#{version}/hanoi-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "hanoi-cli"
  desc "Interactive rebalance advisor for Kubernetes"
  homepage "https://github.com/k-krew/hanoi-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hanoi-cli"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hanoi-cli"]
    end
  end

  # No zap stanza required

end
