# This file was generated by GoReleaser. DO NOT EDIT.
cask "hanoi-cli" do
  version "1.0.1"

  on_macos do
    on_intel do
      url "https://github.com/k-krew/hanoi-cli/releases/download/v#{version}/hanoi-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "de3ebd96a49ba1370462ecd9d277b2541d3cba83dc1758fec5fe472d6ec4eb2e"
    end
    on_arm do
      url "https://github.com/k-krew/hanoi-cli/releases/download/v#{version}/hanoi-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "4d15efc8597f28c94b10f28b3b437e969fa088ba8cc054e10f68b7beebf6b449"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/k-krew/hanoi-cli/releases/download/v#{version}/hanoi-cli_#{version}_linux_amd64.tar.gz"
      sha256 "530188d3c5334dd34b65bd1e13488ec61ec0db5ed542f9b266e3191ab0dd0e23"
    end
    on_arm do
      url "https://github.com/k-krew/hanoi-cli/releases/download/v#{version}/hanoi-cli_#{version}_linux_arm64.tar.gz"
      sha256 "90146238448d1bf977d9f0cbf66b60c667e2faa6efbdeca755cff661b0acb212"
    end
  end

  name "hanoi-cli"
  desc "Interactive rebalance advisor for Kubernetes"
  homepage "https://github.com/k-krew/hanoi-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hanoi-cli"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hanoi-cli"]
    end
  end

  # No zap stanza required

end
