# This file was generated by GoReleaser. DO NOT EDIT.
cask "triplec" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "337205ab477bc5eb6fb935adf9222af72cba161cde42508e326a5d032eb2e861"
      url "https://github.com/k-krew/triplec/releases/download/v#{version}/triplec_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "620bf769d13b66d288fb6bd855dd2b4d44a0e56c81fb50aafb784a0906363124"
      url "https://github.com/k-krew/triplec/releases/download/v#{version}/triplec_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2c1914cafde0e094b8ef7760e836cd7a6f2bfb15153f5d9a6b59a83f7afa9ee9"
      url "https://github.com/k-krew/triplec/releases/download/v#{version}/triplec_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8d825c688bbbb9ef2df9567c6c6d377d25a5cabb041d83df088f2cb526669e44"
      url "https://github.com/k-krew/triplec/releases/download/v#{version}/triplec_#{version}_linux_arm64.tar.gz"
    end
  end

  name "triplec"
  desc "Centralized ACME/TLS manager for air-gapped networks"
  homepage "https://github.com/k-krew/triplec"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "triplec"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/triplec"]
    end
  end

  # No zap stanza required

end
